Repository yiisoft/demo, pull requests merged in 2022-07, with the labels that each got.

#464 Add debugger
  composer.json
  config/common/router.php
Labels: status:code review

#471 Add yii-sentry
  .env.example
  composer.json
  config/.merge-plan.php
  config/common/sentry.php
  config/params.php
Labels: type:task

#473 Fix router command
  src/Command/Router/ListCommand.php
Labels: type:bug

#337 feat: added rate limit
  composer.json
  config/routes.php
  config/web/rate-limit.php
Labels: status:under development
